### PR TITLE
Restart allocation

### PR DESCRIPTION
**Pull request by cshintov**
Restart allocation

I've added allocs page which will allow user to drill down:

`jobs` -> `allocs` -> `tasks`.

Then the admin flow is similar to tasks.

https://github.com/robinovitch61/wander/assets/11365900/c4b909ea-93e7-4ab0-b766-30020c86f4ac

### CODE REVIEW

**Comment by robinovitch61** [comment]
An advantage of wander IMO is that it shows tasks and allocations together without the extra drill down. I've never gotten a request to change this, and am personally annoyed with the web ui's treatment of having to drill down.

Let's keep things at 2 levels, allocs and tasks together, and build task and alloc related admin tasks off the same page.

**Comment by cshintov** [comment]
tasks-allocs-merged-view

focused-on-single-alloc

I get that the drilling down is bad UX in the browser - it's clickety.. clickety.. clickety. I hate the mouse. But on a TUI, it's Enter, Enter, Enter. I'm OK with it.

And maybe also because of the kind of workload I'm dealing with, I value focus over getting there faster.

**Comment by robinovitch61** [comment]
Can you open an issue for this? If there is general support for the change, I'll reconsider it, but for now it seems like personal preference and I'm hesitant to make such a large UX change without more data.

An in between could be making this configurable with the default remaining the mixed view, but then we're maintaining different page sets and forward/back flows for different modes and it'll probably get fairly messy in the implementation.

Either way, let's open an issue, continue the discussion there, and continue development on it if/when we get more data.

**Comment by robinovitch61** [comment]
Closing this PR as per discussion conclusion [here](https://github.com/robinovitch61/wander/issues/127#issuecomment-1932436523)

**Pull request closed without merging**
